// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YerbaShop.API.Contexts;

namespace YerbaShop.API.Migrations
{
    [DbContext(typeof(YerbaShopContext))]
    [Migration("20210404092128_AllEntitesAdded")]
    partial class AllEntitesAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("YerbaShop.API.Entities.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Łazy",
                            PostCode = "42-450",
                            Street = "Łazowska 4",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            City = "Łazy",
                            PostCode = "42-450",
                            Street = "Michałowksa 5",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("YerbaShop.API.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("OrderDetailsId")
                        .HasColumnType("int");

                    b.Property<int>("OrderHistoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("OrderPrice")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("OrderDetailsId");

                    b.HasIndex("OrderHistoryId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("YerbaShop.API.Entities.OrderDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("YerbaShop.API.Entities.OrderHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("OrderHistory");
                });

            modelBuilder.Entity("YerbaShop.API.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LongDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductBrand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ProductPrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<double>("ProductWeight")
                        .HasColumnType("float");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "Argentyna",
                            LongDescription = "Yerba mate Amanda Despalada produkowana w argentyńskiej prowincji Missiones. Opakowanie zawiera dosyć grubo pocięte listki yerba mate bez gałązek. Despalada służy szybkiemu pobudzeniu, które wynika z proporcji suszu. Despalada jest zdecydowanie klasyczną mate. A to oznacza, że prócz lekko ziemistego aromatu jest w niej wyczuwalna goryczka.",
                            ProductBrand = "Amanda",
                            ProductImage = "https://www.poyerbani.pl/pol_pl_Amanda-Despalada-Sin-Palo-0-5kg-894_1.png",
                            ProductName = "Amanda Despelada Sin Palo",
                            ProductPrice = 24.99m,
                            ProductWeight = 0.5,
                            ShortDescription = "Yerba Mate Amanda Despalada Sin Palo 0,5 kg to klasyk z Argentyny. Yerba mate bez dodatków, bez patyczków – wyłącznie listki ostrokrzewu paragwajskiego."
                        },
                        new
                        {
                            Id = 2,
                            Country = "Argentyna",
                            LongDescription = "Yerba mate Amanda Despalada produkowana w argentyńskiej prowincji Missiones. Opakowanie zawiera dosyć grubo pocięte listki yerba mate bez gałązek. Despalada służy szybkiemu pobudzeniu, które wynika z proporcji suszu. Despalada jest zdecydowanie klasyczną mate. A to oznacza, że prócz lekko ziemistego aromatu jest w niej wyczuwalna goryczka.",
                            ProductBrand = "Amanda",
                            ProductImage = "https://www.poyerbani.pl/pol_pl_Amanda-Despalada-Sin-Palo-0-5kg-894_1.png",
                            ProductName = "Amanda Despelada Sin Palo",
                            ProductPrice = 41.99m,
                            ProductWeight = 1.0,
                            ShortDescription = "Yerba Mate Amanda Despalada Sin Palo 1 kg to klasyk z Argentyny. Yerba mate bez dodatków, bez patyczków – wyłącznie listki ostrokrzewu paragwajskiego."
                        },
                        new
                        {
                            Id = 3,
                            Country = "Argentyna",
                            LongDescription = "Popijając yerba mate CBSé Energía Guarana, na długo zapomnisz o kawie. Jeśli poszukujesz podwójnego pobudzenia — to właśnie znalazłeś. Atrakcyjne opakowanie kryje susz o słodkawym, lekko korzennym aromacie, który uwodzi nasze zmysły. Delikatny, przyjemny smak niwelujący wyczuwalną goryczkę ukontentuje nie jedno podniebienie. Przemyślane i zaskakujące połączenie yerba mate z naturalnym ekstraktem z owoców guarany. Całość równoważona przez tradycyjne dodatki ziołowe stanowi połączenie idealne.",
                            ProductBrand = "CBSe",
                            ProductImage = "https://www.poyerbani.pl/pol_pl_CBSe-Energia-Guarana-0-5-kg-1016_1.png",
                            ProductName = "CBSe Energia Guarana",
                            ProductPrice = 21.99m,
                            ProductWeight = 0.5,
                            ShortDescription = "Yerba Mate CBSe Energía Guarana to pobudzająca argentyńska yerba z guaraną. Ma łagodny owocowy smak i aromat. Zawiera mnóstwo kofeiny. Prawdziwy bestseller!"
                        },
                        new
                        {
                            Id = 4,
                            Country = "Argentyna",
                            LongDescription = "Popijając yerba mate CBSé Energía Guarana, na długo zapomnisz o kawie. Jeśli poszukujesz podwójnego pobudzenia — to właśnie znalazłeś. Atrakcyjne opakowanie kryje susz o słodkawym, lekko korzennym aromacie, który uwodzi nasze zmysły. Delikatny, przyjemny smak niwelujący wyczuwalną goryczkę ukontentuje nie jedno podniebienie. Przemyślane i zaskakujące połączenie yerba mate z naturalnym ekstraktem z owoców guarany. Całość równoważona przez tradycyjne dodatki ziołowe stanowi połączenie idealne.",
                            ProductBrand = "CBSe",
                            ProductImage = "https://www.poyerbani.pl/pol_pl_CBSe-Energia-Guarana-0-5-kg-1016_1.png",
                            ProductName = "CBSe Energia Guarana",
                            ProductPrice = 39.99m,
                            ProductWeight = 1.0,
                            ShortDescription = "Yerba Mate CBSe Energía Guarana to pobudzająca argentyńska yerba z guaraną. Ma łagodny owocowy smak i aromat. Zawiera mnóstwo kofeiny. Prawdziwy bestseller!"
                        },
                        new
                        {
                            Id = 5,
                            Country = "Argentyna",
                            LongDescription = "CBSé Pomelo to owocowa yerba mate o smaku grejpfruta. W sam raz do tereré. Klasyczna i delikatna elaborada w argentyńskim stylu została uzupełniona cytrusową dominantą, która przenosi w świat egzotyki. Ciekawa propozycja dla miłośników owocowych smaków. Także dla rozpoczynających swoją yerbacianą odyseję.",
                            ProductBrand = "CBSe",
                            ProductImage = "https://www.poyerbani.pl/pol_pl_CBSe-Pomelo-0-5kg-grejpfrut-1039_1.png",
                            ProductName = "CBSe Pomelo(grejpfrut)",
                            ProductPrice = 21.99m,
                            ProductWeight = 0.5,
                            ShortDescription = "Grejfrutowa Yerba Mate znanej marki CBSe"
                        },
                        new
                        {
                            Id = 6,
                            Country = "Argentyna",
                            LongDescription = "Kraus Orgánica to yerba mate absolutnie naturalna. Jej krzewy wzrastają na ekologicznej plantacji w zgodzie ze środowiskiem. Zbiory są limitowane ze względu na charakter uprawy, wolnej od środków ochrony i stymulacji chemicznej. Także innowacyjna metoda suszenia surowca czyni Krausa wyjątkowym.. Zazwyczaj yerba mate jest suszona (wędzona) w dymie ogniska, tutaj zastosowano innowacyjną technologię suszenia za pomocą gorącego powietrza. Taka metoda uwalnia napar od dymnego i ostrzejszego posmaku. Kraus Orgánica jest nadal gorzką yerbą, ale o nieco trawiastym (świeżym) posmaku. Łagodny smak pobudzenia. Polecamy.",
                            ProductBrand = "Kraus",
                            ProductImage = "https://www.poyerbani.pl/pol_pl_Kraus-Organica-0-5kg-organiczna-1218_2.png",
                            ProductName = "Kraus Organica",
                            ProductPrice = 25.99m,
                            ProductWeight = 0.5,
                            ShortDescription = "Kraus to argentyńska marka specjalizująca się w produkcji Yerba Mate bez użycia dymu. Liście suszone są gorącym powietrzem, dzięki czemu zachowują żywy kolor. "
                        },
                        new
                        {
                            Id = 7,
                            Country = "Argentyna",
                            LongDescription = "Cruz de Malta Elaborada Con Palo to tradycyjna yerba mate z patyczkami pozbawiona dodatków smakowych. Należy do najbardziej znanych argentyńskich marek o dużej renomie i długich tradycjach. Cruz De Malta od zawsze utożsamiano z wysokimi standardami produkcji i wyśmienitym smakiem. Jest świetnym źródłem mateiny gwarantującej długotrwały efekt",
                            ProductBrand = "Molinos",
                            ProductImage = "https://www.poyerbani.pl/pol_pl_Cruz-de-Malta-Elaborada-Con-Palo-1kg-1067_1.png",
                            ProductName = "Cruz de Malta Elaborada Con Paloa",
                            ProductPrice = 39.99m,
                            ProductWeight = 1.0,
                            ShortDescription = "Cruz de Malta to argentyńska marka Yerba Mate produkowana od 1874 roku na plantacjach należących do Molinos Rio de la Plata."
                        },
                        new
                        {
                            Id = 8,
                            Country = "Argentyna",
                            LongDescription = "Cruz de Malta Elaborada Con Palo to tradycyjna yerba mate z patyczkami pozbawiona dodatków smakowych. Należy do najbardziej znanych argentyńskich marek o dużej renomie i długich tradycjach. Cruz De Malta od zawsze utożsamiano z wysokimi standardami produkcji i wyśmienitym smakiem. Jest świetnym źródłem mateiny gwarantującej długotrwały efekt",
                            ProductBrand = "Molinos",
                            ProductImage = "https://www.poyerbani.pl/pol_pl_Cruz-de-Malta-Elaborada-Con-Palo-1kg-1067_1.png",
                            ProductName = "Cruz de Malta Elaborada Con Paloa",
                            ProductPrice = 19.99m,
                            ProductWeight = 0.5,
                            ShortDescription = "Cruz de Malta to argentyńska marka Yerba Mate produkowana od 1874 roku na plantacjach należących do Molinos Rio de la Plata."
                        },
                        new
                        {
                            Id = 9,
                            Country = "Paragwaj",
                            LongDescription = "Kurupi Clasica - klasyczna paragwajska elaborada, przechodząca specjalny proces obróbki, w którym uzyskuje swój unikalny i niepowtarzalny smak. Jest jedną z mocniejszych yerba mate, której walory docenią szczególnie doświadczeni mateiści. Szczególnie poszukujący wyrazistego smaku oraz dobrego pobudzenia znajdą w Kurupi Clásica źródło naturalnej przyjemności. Posiada wspaniały goryczkowaty smak i dymny aromat. Ze względu na długi czas sezonowania jest nieco łagodniejsza od bliźniaczej Kurupi Tradicional. Pięknie pieniący susz jest głównym atutem tej popularnej mate.",
                            ProductBrand = "Kurupi",
                            ProductImage = "https://www.poyerbani.pl/pol_pl_Kurupi-Clasica-0-5kg-1228_1.png",
                            ProductName = "Kurupi Clasica",
                            ProductPrice = 21.99m,
                            ProductWeight = 0.5,
                            ShortDescription = "Kurupi Clásica 500 g 0,5 kg to paragwajska yerba mate w klasycznym stylu. Cechuje się wspaniałym, szlachetnie goryczkowym aromatem i świetnie pobudza."
                        },
                        new
                        {
                            Id = 10,
                            Country = "Paragwaj",
                            LongDescription = "Yerba mate Kurupi Katuava Especial to najwyższej jakości paragwajska yerba mate z dodatkiej ciętej katuavy, prawdziwego skarbu południowoamerykańskiej ziemi. Najcenniejszym elementem rośliny jest jej kora cechująca się wspaniałym eterycznym aromatem. Tradycyjna medycyna ludowa przypisuje jej właściwości przeciwzapalne i oczyszczające i powszechnie uznaje za afrodyzjak. W niektórych regionach Brazylii mawia się ponoć, że po 60 roku życia, każdy mężczyzna \"należy\" do katuavy. Jak sproszkowana kora tej tajemniczej rośliny wypada w połączeniu z yerba mate? Naprawdę znakomicie! Szlachetna goryczka dymionej paragwajskiej yerba mate jest zręcznie harmonizowana przez ziołowe akcenty. Nie mamy wątpliwości, że całość doskonale odnajdzie się jako baza dla orzeźwiającego tereré w upalne dni, jak również w formie ciepłego naparu na rozgrzanie. Warto zaznaczyć, że podobnie jak inne produkty marki, Kurupi Katuava Especial cechuje się dużą zawartością naturalnej kofeiny. Będzie doskonałym źródłem naturalnej enegii. Polecamy ją przede wszystkim miłośnikom ziołowych yerba mate i doświadczonym mateistom zainteresowanym rasowymi paragwajskimi yerba mate.",
                            ProductBrand = "Kurupi",
                            ProductImage = "https://www.poyerbani.pl/pol_pl_Kurupi-Katuava-Especial-0-5kg-1234_1.png",
                            ProductName = "Kurupi Katuava",
                            ProductPrice = 21.99m,
                            ProductWeight = 0.5,
                            ShortDescription = "Kurupi Katuava Especial 500 g to paragwajska yerba mate z dodatkiem kory catuaby oraz zioła burrito. Ziołowy aromat równoważy goryczkę. Doskonale pobudza."
                        },
                        new
                        {
                            Id = 11,
                            Country = "Paragwaj",
                            LongDescription = "Yerba mate Kurupi Katuava Especial to najwyższej jakości paragwajska yerba mate z dodatkiej ciętej katuavy, prawdziwego skarbu południowoamerykańskiej ziemi. Najcenniejszym elementem rośliny jest jej kora cechująca się wspaniałym eterycznym aromatem. Tradycyjna medycyna ludowa przypisuje jej właściwości przeciwzapalne i oczyszczające i powszechnie uznaje za afrodyzjak. W niektórych regionach Brazylii mawia się ponoć, że po 60 roku życia, każdy mężczyzna \"należy\" do katuavy. Jak sproszkowana kora tej tajemniczej rośliny wypada w połączeniu z yerba mate? Naprawdę znakomicie! Szlachetna goryczka dymionej paragwajskiej yerba mate jest zręcznie harmonizowana przez ziołowe akcenty. Nie mamy wątpliwości, że całość doskonale odnajdzie się jako baza dla orzeźwiającego tereré w upalne dni, jak również w formie ciepłego naparu na rozgrzanie. Warto zaznaczyć, że podobnie jak inne produkty marki, Kurupi Katuava Especial cechuje się dużą zawartością naturalnej kofeiny. Będzie doskonałym źródłem naturalnej enegii. Polecamy ją przede wszystkim miłośnikom ziołowych yerba mate i doświadczonym mateistom zainteresowanym rasowymi paragwajskimi yerba mate.",
                            ProductBrand = "Kurupi",
                            ProductImage = "https://www.poyerbani.pl/pol_pl_Kurupi-Katuava-Especial-0-5kg-1234_1.png",
                            ProductName = "Kurupi Katuava",
                            ProductPrice = 40.99m,
                            ProductWeight = 1.0,
                            ShortDescription = "Kurupi Katuava Especial 1kg to paragwajska yerba mate z dodatkiem kory catuaby oraz zioła burrito. Ziołowy aromat równoważy goryczkę. Doskonale pobudza."
                        },
                        new
                        {
                            Id = 12,
                            Country = "Paragwaj",
                            LongDescription = "Yerba mate Pajarito Elaborada to klasyka z Paragwaju. Pajarito oznacza po hiszpańsku „ptaszek” i na nazwie kończy się delikatności. Mocna w działaniu i wyraźna w smaku. Tu nie ma miejsca na subtelności - to jest mate w stylu macho. Wielu mateistów mówiąc yerba, myśli właśnie Elaborada od Pajarito. Być może dlatego, że kto jej spróbował, ten długo pamięta wyjątkowo przyjemny smak. Jedna z tych odmian, które dostarczają energii na długo. Tajemnicą firmy jest sposób yerba mate. Wiemy o nim tyle, że zbiera się tylko najlepsze listki i gałązki. W późniejszym etapie specjalne receptury przygotowania i palenia czynią z niej jedną z najlepszych mate na świecie. Pozostawia wyrazisty smak i przyjemne wspomnienia.",
                            ProductBrand = "Pajarito",
                            ProductImage = "https://www.poyerbani.pl/pol_pl_Pajarito-Elaborada-Con-Palo-Tradicional-1kg-1327_1.png",
                            ProductName = "Pajarito Elaborada Con Palo",
                            ProductPrice = 29.99m,
                            ProductWeight = 1.0,
                            ShortDescription = "Pajarito Elaborada Con Palo Tradicional 1 kg to tradycyjna yerba mate z Paragwaju. Ma mocny dymny aromat i wyrazisty smak. Dobrze pobudza."
                        },
                        new
                        {
                            Id = 13,
                            Country = "Paragwaj",
                            LongDescription = "Pajarito Hierbas to idealna propozycja dla osób gustujących w ziołowych mieszankach. Kompozycja składa się w 90% z yerba mate oraz w 10% z aromatycznych ziół. Między innymi: mięty pieprzowej, cedronu oraz burito. Orzeźwiający smak przyjemnie pobudza.",
                            ProductBrand = "Pajarito",
                            ProductImage = "https://www.poyerbani.pl/pol_pl_Pajarito-Elaborada-Con-Palo-Tradicional-1kg-1327_1.png",
                            ProductName = "Pajarito Compuesta con Hierbas",
                            ProductPrice = 21.99m,
                            ProductWeight = 0.5,
                            ShortDescription = "Pajarito Compuesta con Hierbas 0,5 kg 500 g to ziołowa yerba mate z Paragwaju. Ma goryczkowy aromat połączony z rześkim dodatkiem mięty. Dobrze pobudza. Hit naszego sklepu yerba mate!"
                        },
                        new
                        {
                            Id = 14,
                            Country = "Paragwaj",
                            LongDescription = "Pochodząca z ekologicznej uprawy jest specjalnie selekcjonowana dla osiągnięcia wyrazistszego smaku, a przez to doskonałego pobudzenia. Rodzinna plantacja uczestniczy w programie odbudowy lasów tropikalnych. Sięgając zatem po tę mocną mate, pomagasz ocalić unikalne środowisko. Część surowca leżakuje niemal cały rok dla wydobycia intensywności smaku i aromatu. La Rubia dosłownie znaczy po hiszpańsku „blondynka”. Ta dama należy do grona wielbicielek wytrawnych smaków w najlepszym wydaniu.",
                            ProductBrand = "La Rubia",
                            ProductImage = "https://www.poyerbani.pl/pol_pl_La-Rubia-Elaborada-Con-Palo-Tradicional-0-5kg-1254_2.png",
                            ProductName = "La Rubia Elaborada Con Palo",
                            ProductPrice = 21.99m,
                            ProductWeight = 0.5,
                            ShortDescription = "La Rubia 0,5 kg 500 g to paragwajska yerba mate z organicznym certyfikatem. Nie zawiera dodatków. Cechuje się klasycznym goryczkowym smakiem i świetnie pobudza."
                        },
                        new
                        {
                            Id = 15,
                            Country = "Paragwaj",
                            LongDescription = "Pochodząca z ekologicznej uprawy jest specjalnie selekcjonowana dla osiągnięcia wyrazistszego smaku, a przez to doskonałego pobudzenia. Rodzinna plantacja uczestniczy w programie odbudowy lasów tropikalnych. Sięgając zatem po tę mocną mate, pomagasz ocalić unikalne środowisko. Część surowca leżakuje niemal cały rok dla wydobycia intensywności smaku i aromatu. La Rubia dosłownie znaczy po hiszpańsku „blondynka”. Ta dama należy do grona wielbicielek wytrawnych smaków w najlepszym wydaniu.",
                            ProductBrand = "La Rubia",
                            ProductImage = "https://www.poyerbani.pl/pol_pl_La-Rubia-Elaborada-Con-Palo-Tradicional-0-5kg-1254_2.png",
                            ProductName = "La Rubia Elaborada Con Palo",
                            ProductPrice = 40.99m,
                            ProductWeight = 1.0,
                            ShortDescription = "La Rubia 1kg to paragwajska yerba mate z organicznym certyfikatem. Nie zawiera dodatków. Cechuje się klasycznym goryczkowym smakiem i świetnie pobudza."
                        },
                        new
                        {
                            Id = 16,
                            Country = "Argentyna",
                            LongDescription = "Yerba Mate Taragüi Energia to produkt Establecimiento Las Marias, jednego z największych producentów yerba mate w Argentynie. Należy do najpopularniejszych mate oferowanych przez to przedsiębiorstwo. Wszystko ze względu na dużą zawartość naturalnej kofeiny. Według producenta jest jej nawet 30% więcej niż w tradycyjnych yerba mate. Co ciekawe, w przeciwieństwie do innych produktów znancych z silnego efektu pobudzajacego, Taragüi Energia nie zawiera żadnych dodatków. Co sprawia więc, że tak dobrze energetyzuje? Kluczem okazuje się odpowiednia technika przetwarzania suszu. Taragui Energia to silnie energetyzująca yerba mate w klasycznej otoczce smakowej. Koniecznie sprawdźcie jej działanie!",
                            ProductBrand = "Las Marias",
                            ProductImage = "https://www.poyerbani.pl/pol_pl_Taragui-Energia-0-5kg-1671_1.png",
                            ProductName = "Taragui Energia",
                            ProductPrice = 22.99m,
                            ProductWeight = 0.5,
                            ShortDescription = "Yerba Mate Taragüi Energia to klasyczna yerba o zwiększonej zawartości kofeiny, dzięki czemu daje mocny efekt pobudzenia."
                        },
                        new
                        {
                            Id = 17,
                            Country = "Argentyna",
                            LongDescription = "Yerba Mate Taragüi Energia to produkt Establecimiento Las Marias, jednego z największych producentów yerba mate w Argentynie. Należy do najpopularniejszych mate oferowanych przez to przedsiębiorstwo. Wszystko ze względu na dużą zawartość naturalnej kofeiny. Według producenta jest jej nawet 30% więcej niż w tradycyjnych yerba mate. Co ciekawe, w przeciwieństwie do innych produktów znancych z silnego efektu pobudzajacego, Taragüi Energia nie zawiera żadnych dodatków. Co sprawia więc, że tak dobrze energetyzuje? Kluczem okazuje się odpowiednia technika przetwarzania suszu. Taragui Energia to silnie energetyzująca yerba mate w klasycznej otoczce smakowej. Koniecznie sprawdźcie jej działanie!",
                            ProductBrand = "Las Marias",
                            ProductImage = "https://www.poyerbani.pl/pol_pl_Taragui-Energia-0-5kg-1671_1.png",
                            ProductName = "Taragui Energia",
                            ProductPrice = 32.99m,
                            ProductWeight = 1.0,
                            ShortDescription = "Yerba Mate Taragüi Energia to klasyczna yerba o zwiększonej zawartości kofeiny, dzięki czemu daje mocny efekt pobudzenia."
                        },
                        new
                        {
                            Id = 18,
                            Country = "Argentyna",
                            LongDescription = "Taragüi Maracuya Tropical - delikatna yerba o złagodzonej goryczce. Łagodny smak i aromat zdecydowanie występują w naturalnych odmianach klasyki. Polecana szczególnie wszystkim początkującym mateistom. Sprawdzona jako doskonały poczęstunek dla zainteresowanych niezwykłymi właściwościami yerba mate. Ciekawym dodatkiem jest świetnie wkomponowana nuta marakui. ",
                            ProductBrand = "Las Marias",
                            ProductImage = "https://www.poyerbani.pl/pol_pl_Taragui-Maracuya-Tropical-marakuja-0-5kg-1509_1.png",
                            ProductName = "Taragui Maracuya Tropical",
                            ProductPrice = 22.99m,
                            ProductWeight = 0.5,
                            ShortDescription = "Taragüi Maracuya Tropical 0,5 kg 500 g to argentyńska yerba mate o smaku owocu marakui. Doskonale pobudza, jest świetna na zimno i na ciepło."
                        },
                        new
                        {
                            Id = 19,
                            Country = "Brazylia",
                            LongDescription = "Zanieczyszczenie powietrza, niezdrowe jedzenie, stres i nieustanny pośpiech to codzienność człowieka XXI wieku. Istnieje jednak naturalne remedium na bolączki życia w betonowej dżungli. To Verde Mate Detox! Spróbuj koniecznie! ",
                            ProductBrand = "Verde Mate",
                            ProductImage = "https://www.poyerbani.pl/pol_pl_Verde-Mate-Green-Detox-0-5kg-4425_1.png",
                            ProductName = "Verde Mate Green Detox",
                            ProductPrice = 24.99m,
                            ProductWeight = 0.5,
                            ShortDescription = "Verde Mate Green Detox to idealna propozycja dla każdego, kto poszukuje wytrawnego i dobrze wyważonego smaku yerba mate."
                        },
                        new
                        {
                            Id = 20,
                            Country = "Brazylia",
                            LongDescription = "Dawno nie spotkaliśmy nic lepszego od Verde Mate Frutos del Bosque. Nasze europejskie owoce leśne to idealny materiał do produkcji soków, dżemów, win i nalewek. A gdyby tak połączyć je ze świeżą brazylijską yerba mate, która dorasta w dzikim tropikalnym lesie w cieniu drzew araukarii chilijskiej? Idealna harmonia! Kompozycja jest urozmaicona wizualnie. Poza yerba mate w składzie mamy starannie wyselekcjonowane owoce dzikiej róży, jeżyny i czerwonej porzeczki oraz malinowe liście. Gwarancja pobudzenia w świeżym stylu! ",
                            ProductBrand = "Verde Mate",
                            ProductImage = "https://www.poyerbani.pl/pol_pl_Verde-Mate-Green-Frutos-del-Bosque-0-5kg-4480_1.png",
                            ProductName = "Verde Mate Green Frutos del Bosque",
                            ProductPrice = 22.99m,
                            ProductWeight = 0.5,
                            ShortDescription = "Verde Mate Frutos del Bosque to połączenie aromatycznej yerba mate ze słodkawymi i kwaskowatymi owocami z europejskich lasów."
                        },
                        new
                        {
                            Id = 21,
                            Country = "Brazylia",
                            LongDescription = "Odkryj moc naturalnej kofeiny i cennych dla zdrowia składników w prawdziwie zmysłowej odsłonie! Verde Mate Más IQ to doskonale dopracowana kompozycja ziół, owoców i yerba mate. Oprócz listków ostrokrzewu z leśnej uprawy w brazylijskim stanie Parana, Mas IQ zawiera wyciąg z ginkgo biloba oraz żeń-szeń. Ziołową bazę uzupełniają owocowe dodatki w postaci skórki pomarańczy i kawałków ananasa. Kompozycję zamyka znany z dużej zawartości kofeiny ekstrakt z guarany. Po Verde Mate Mas IQ najchętniej sięgają uczniowie, studenci, informatycy i inne osoby pracujące umysłowo.",
                            ProductBrand = "Verde Mate",
                            ProductImage = "https://www.poyerbani.pl/pol_pl_Verde-Mate-Green-Mas-IQ-0-5kg-4240_1.png",
                            ProductName = "Verde Mate Green Mas IQ",
                            ProductPrice = 27.99m,
                            ProductWeight = 0.5,
                            ShortDescription = "Verde Mate Más IQ to kompozycja ostrokrzewu paragwajskiego i składników nadających jej delikatnie owocowy smak. Nie brakuje w niej także pożytecznych dodatków!"
                        });
                });

            modelBuilder.Entity("YerbaShop.API.Entities.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ReviewText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeOfReview")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProductId = 1,
                            ReviewText = "Smaczna Yerba polecam!",
                            TypeOfReview = "Like",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            ProductId = 1,
                            ReviewText = "Bardzo dobra klasyczna Yerba!",
                            TypeOfReview = "Like",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("YerbaShop.API.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressId = 1,
                            Email = "tomus@gmail.com",
                            FirstName = "Tomasz",
                            LastName = "Kowalski",
                            Password = "qwerty"
                        },
                        new
                        {
                            Id = 2,
                            AddressId = 2,
                            Email = "michalek@gmail.com",
                            FirstName = "Michał",
                            LastName = "Nogalski",
                            Password = "qwerty"
                        });
                });

            modelBuilder.Entity("YerbaShop.API.Entities.Address", b =>
                {
                    b.HasOne("YerbaShop.API.Entities.User", "User")
                        .WithOne("Address")
                        .HasForeignKey("YerbaShop.API.Entities.Address", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("YerbaShop.API.Entities.Order", b =>
                {
                    b.HasOne("YerbaShop.API.Entities.OrderDetails", "OrderDetails")
                        .WithMany()
                        .HasForeignKey("OrderDetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YerbaShop.API.Entities.OrderHistory", "OrderHistory")
                        .WithMany("Orders")
                        .HasForeignKey("OrderHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderDetails");

                    b.Navigation("OrderHistory");
                });

            modelBuilder.Entity("YerbaShop.API.Entities.OrderDetails", b =>
                {
                    b.HasOne("YerbaShop.API.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("YerbaShop.API.Entities.OrderHistory", b =>
                {
                    b.HasOne("YerbaShop.API.Entities.User", "User")
                        .WithMany("OrdersHistory")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("YerbaShop.API.Entities.Review", b =>
                {
                    b.HasOne("YerbaShop.API.Entities.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YerbaShop.API.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("YerbaShop.API.Entities.OrderHistory", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("YerbaShop.API.Entities.Product", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("YerbaShop.API.Entities.User", b =>
                {
                    b.Navigation("Address");

                    b.Navigation("OrdersHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
